Repository francep2p/community, pull requests merged in 2019-08, with the labels that each got.

#19 Create talk proposal template
  .github/ISSUE_TEMPLATE/talk_proposal.md
Labels: ✅ Approved

#20 Update Readme.md
  README.md
Labels: ✅ Approved

#23 Update proposal link
  README.md
Labels: 🔍 Ready for Review

#26 Update talk_proposal.md
  .github/ISSUE_TEMPLATE/talk_proposal.md
Labels: 🔍 Ready for Review

#27 Create workshop proposal template
  .github/ISSUE_TEMPLATE/workshop_proposal.md
Labels: 🔍 Ready for Review

#34 chore: paris & lyon p2p logo propsals
  assets/logos/france_p2p_blue.png
  assets/logos/france_p2p_blue.svg
  assets/logos/france_p2p_red.png
  assets/logos/france_p2p_red.svg
  assets/logos/france_p2p_white.png
  assets/logos/france_p2p_white.svg
  assets/logos/lyon_p2p_no_border_regular.png
  assets/logos/lyon_p2p_no_border_regular.svg
  assets/logos/lyon_p2p_no_border_small.png
  assets/logos/lyon_p2p_no_border_small.svg
  assets/logos/paris_p2p_no_border_regular.png
  assets/logos/paris_p2p_no_border_regular.svg
  assets/logos/paris_p2p_no_border_small.png
  assets/logos/paris_p2p_no_border_small.svg
Labels: ✅ Approved, 🔍 Ready for Review

#40 chore: reorganise folder and add new version for Lyon P2P logo
  assets/logos/france/france_p2p_blue.png
  assets/logos/france/france_p2p_blue.svg
  assets/logos/france/france_p2p_red.png
  assets/logos/france/france_p2p_red.svg
  assets/logos/france/france_p2p_white.png
  assets/logos/france/france_p2p_white.svg
  assets/logos/lyon/v1/lyon_p2p_no_border_regular.png
  assets/logos/lyon/v1/lyon_p2p_no_border_regular.svg
  assets/logos/lyon/v1/lyon_p2p_no_border_small.png
  assets/logos/lyon/v1/lyon_p2p_no_border_small.svg
  assets/logos/lyon/v2/lyon_p2p_no_border_regular.png
  assets/logos/lyon/v2/lyon_p2p_no_border_regular.svg
  assets/logos/paris/paris+p2p_small.png
  assets/logos/paris/paris+p2p_small.svg
  assets/logos/paris/paris_p2p.png
  assets/logos/paris/paris_p2p.svg
  assets/logos/paris/paris_p2p_favicon.png
  assets/logos/paris/paris_p2p_favicon.svg
  assets/logos/paris/paris_p2p_no_border_regular.png
  assets/logos/paris/paris_p2p_no_border_regular.svg
  assets/logos/paris/paris_p2p_no_border_small.png
  assets/logos/paris/paris_p2p_no_border_small.svg
Labels: ✅ Approved

#42 chore: Update README.md
  README.md
Labels: ✅ Approved

#39 chore: add link to Proposals Kanban
  README.md
Labels: ✅ Approved
